export { default as AboutUs } from './Website/AboutUs.jsx';
export { default as Blog } from './Website/Blog.jsx';
export { default as CTA } from './Website/CTA.jsx';
export { default as Bottom } from './Website/Bottom.jsx';
export { default as HeroSection } from './Website/HeroSection.jsx';
export { default as MenuSection } from './Website/MenuSection.jsx';
export { default as Navbar } from './Website/Navbar.jsx';
export { default as ServiceSection } from './Website/ServiceSection.jsx';
export { default as TeamSection } from './Website/TeamSection.jsx';